apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwdemo
  labels:
    app: fwdemo
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1725743246639
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwdemo
  template:
    metadata:
      labels:
        app: fwdemo
    spec:
      containers:
        - name: fwdemo
          image: acrworkflow1725743246639.azurecr.io/image-workflow-1725743246639:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
