apiVersion: v1
kind: Service
metadata:
  name: fwdemo
  namespace: namespace-workflow-1725743246639
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: fwdemo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000